### PR TITLE
New pumpkin and corn icons

### PR DESCRIPTION
**Pull request by jsimplicio**
screen shot 2016-01-23 at 12 09 19 pm

### CODE REVIEW

**Comment by simonv3** [comment]
:+1: This looks excellent. @andru is this the kind of file structure you had in mind?

**Comment by andru** [comment]
structure LGTM!  

@jsimplicio do you know how to do an interactive rebase? It'd be good to have a single commit for each icon so the git history of the main repo stays clean.

Edit: by each icon I mean each crop; a commit for the three corn icons and another commit for the three pumpkin icons

**Comment by simonv3** [comment]
Here's a pretty good step by step on rebasing: https://help.github.com/articles/about-git-rebase/

From memory, so may be a bit faulty: you'll want to rebase against master `git rebase -i master` and then you can replace the word "pick" with "squash" and that will magically combine your commits into one. 

I'm personally not too fussed about a clean commit history, and I also suspect that most people will just be adding all of their crops in one commit. There'll probably also be more designers contributing than experienced git users.

**Comment by andru** [comment]
> I'm personally not too fussed about a clean commit history

Aye. It's not really a big deal. It'd be sweet to have a simple history of one commit each time an icon set is edited or revised so we can keep track of who did what without having to wade through a lot of redundant commits, but it's not the end of the world if it's not clean.

@jsimplicio if you know how to do it, go for it. If not, no worries. The icons are sweet and I'm happy either way.

**Comment by jsimplicio** [comment]
Agh sorry about being so late on this, I checked it then forgot about it. Do you still want me to do anything about it? Cheers

**Comment by simonv3** [comment]
Eh, it's been merged. We're still pretty early, so I guess technically I could re-write the history, but I'm not too fussed. 

I had a look at the SVG files themselves - I'm wondering whether it makes sense to put each element on its own line, that way it's easy to see whether something in the SVG has been edited, and where that edit was. Though that might be too much effort, it'd be a nice thing to aspire to. Thoughts?

**Pull request merged**
